services:
  - type: web
    name: rtsp-stream-viewer-backend
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: daphne backend.asgi:application --port $PORT --bind 0.0.0.0
    autoDeploy: true
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-secret-key"
